### PR TITLE
Added getResponseHeaders()

### PR DESCRIPTION
**Pull request by VIEWSION**
I implemented the possibility to fetch the latest response headers. This is pretty helpful to track the rate limits without any extra call. Just use $yourWebshopappApiClient->getResponseHeaders(); after you made an API call and receive an array of all response headers like
...
[X-RateLimit-Limit] => 300/3000/12000
[X-RateLimit-Remaining] => 298/2965/11910
[X-RateLimit-Reset] => 202/802/8002
...

### CODE REVIEW

**Comment by FerdivdWoerd** [comment]
We would also very much like to use the headers. Any chance this PR is getting accepted soon?

**Comment by redelschaap** [comment]
This would be a great feature!

**Comment by TimBloembergen** [comment]
A ticket has been created for our dev team to get this PR merged. Stay tuned 👍

**Comment by redelschaap** [comment]
Great news!

**Comment by FerdivdWoerd** [comment]
Can't wait!

**Comment by redelschaap** [comment]
Any news on this?

**Comment by TimBloembergen** [comment]
@redelschaap no news on this. We currently do not have dev resources available to deploy this. With a PR like this we need to re-generate the client and publish it. This takes some time.

**Comment by FerdivdWoerd** [comment]
Any news if this is getting merged soon?

**Comment by TimothyGs** [comment]
@FerdivdWoerd @VIEWSION @redelschaap this change has been accepted and put in the latest release, version 1.9.0. Please check the readme on how to implement this, as it is exactly as @VIEWSION suggested.

Thanks, and feel free to add feature requests, I'll try to evaluate them as fast as I can and try to keep communication open. 

Closing this PR as it has been fixed in rc1.9.0 https://github.com/SEOshop/API-PHP-Client/pull/31

**Pull request closed without merging**
