### PR TITLE
Added support for sets

### PR DESCRIPTION
**Pull request by TheDevilOnLine**
Added support for sets (http://developers.seoshop.com/api/resources/set) to the API.

### CODE REVIEW

**Comment by jeroenvisser101** [comment]
Hi Tom! Thanks for your contribution, I'll ask my colleague to put this in the generator.

**Comment by michielrensen** [comment]
@TheDevilOnLine As the API-client is generated, I cannot merge your PR, but I will release a new version of the client which includes this endpoint. Thanks for the headsup!

**Comment by michielrensen** [comment]
Just released v1.5 which includes support for sets and additionalCosts

**Comment by TheDevilOnLine** [comment]
Quick question @michielrensen / @jeroenvisser101 : How can you apply a 'set' to a 'product' via the API (I was working in this when I found the set missing from the API)?

**Comment by michielrensen** [comment]
@TheDevilOnLine you can do this at the [Product](http://developers.seoshop.com/api/resources/product) resource, look for the PUT example, it explains how to do that. Basically you can set the Set (no pun intended) and choose which variants should be created in one call. 
It's maybe not as consistent with the rest of the API, but at least it saves you from having to make multiple calls.

**Comment by TheDevilOnLine** [comment]
@michielrensen I've send you an e-mail with a bugreport (seems like setting a set breaks something)

**Pull request closed without merging**
