### PR TITLE
Fixed the 'Update the productAttribute resource of a shop in bulk' call

### PR DESCRIPTION
**Pull request by nedelenbos**
We tried to use the productAttribute bulk call (http://developers.seoshop.com/api/resources/productattribute), but the API returned an error. 
In this pull request we fixed this issue.

### CODE REVIEW

**Comment by jeroenvisser101** [comment]
@nedelenbos Hi! Thanks for this PR, @michielrensen will review this, and see if we can add it to our generator (as the client is generated)

Thanks a lot!

**Comment by jeroenvisser101** [comment]
@nedelenbos I'm really sorry that this took so long. I'm planning on changing the generator next week (in case you didn't know, our API is generated) to include this fix. I'll keep you posted!

**Comment by jeroenvisser101** [comment]
I added a similar method to the generator, which will be released in v1.6.0

**Comment by nedelenbos** [comment]
Thanks! Any ETA on when v1.6.0 will be released?

**Comment by jeroenvisser101** [comment]
Working on it as we speak, so I will test it with a colleague and try to get it on packagist today! The function signature changed a bit. If you want, you can 'watch' this repo and get a notification once something changes :

**Comment by jeroenvisser101** [comment]
@nedelenbos can you confirm that it works in v1.6.0-rc?

`"seoshop/seoshop-php": "1.6.0-rc"`

**Comment by nedelenbos** [comment]
@jeroenvisser101 I can confirm that this works correctly now!  You can close this pull request. Thanks for your update :+1:

**Comment by jeroenvisser101** [comment]
Thanks! 1.6.0 will be released today if no other regressions are found

**Pull request closed without merging**
